Alya Safadella Putri Akca \
221910892 \
3SI1 \
Tugas 11 APG

In [1]:
library(expm)
library(openxlsx)

Loading required package: Matrix


Attaching package: 'expm'


The following object is masked from 'package:Matrix':

    expm




# 10.10

In a study of poverty, crime, and deterrence, Parker and Smith [10] report certain summary crime statistics in various states for the years 1970 and 1973. A 
portion of their sample correlation matrix is 

$X_{1}^{(1)}$ = 1973 nonprimary homicides \
$X_{2}^{(1)}$ = 1973 primary homicides (homicides involving family or acquaintances) \
$X_{1}^{(2)}$ = 1970 severity of punishment (median months served) \
$X_{2}^{(2)}$ = 1970 certainty of punishment (number of admissions to prison 
divided by number of homicides)

In [2]:
R11_10 <- matrix(c(1, .615,
                .615, 1),2,2)
R12_10 <- matrix(c(-.111, -.266,
                -.195, -.085),2,2)
R21_10 <- matrix(c(-.111, -.195,
                -.266, -.085),2,2)
R22_10 <- matrix(c(1, -.269,
                -.269, 1),2,2)

## (a) Find the sample canonical correlations

### Canonical Correlation for Result 1

In [3]:
result1_10 <- sqrtm(solve(R11_10))%*%R12_10%*%solve(R22_10)%*%R21_10%*%sqrtm(solve(R11_10))
result1_10

[,1]       [,2]      
[1,] 0.04589913 0.02741096
[2,] 0.02741096 0.08438906

In [4]:
eigenvalue1_10 <- eigen(result1_10)$value
eigenvalue1_10

[1] 0.09863632 0.03165187

In [5]:
eigenvector1_10 <- eigen(result1_10)$vectors
eigenvector1_10

[,1]      [,2]      
[1,] 0.4611887 -0.8873021
[2,] 0.8873021  0.4611887

In [6]:
a1_result1_10 <- sqrtm(solve(R11_10))%*%eigenvector1_10[,1]
a1_result1_10

[,1]     
[1,] 0.1871847
[2,] 0.8739285

In [7]:
b1_result1_10 <- solve(R22_10)%*%R21_10%*%a1_result1_10
b1_result1_10

[,1]      
[1,] -0.3051226
[2,] -0.1928629

In [8]:
scale_result1_10 <- 1/(sqrtm(t(b1_result1_10)%*%R22_10%*%b1_result1_10))
newb1_result1_10 <- (scale_result1_10[1,1])*b1_result1_10
newb1_result1_10

[,1]      
[1,] -0.9715295
[2,] -0.6140876

In [9]:
# canonical correlation 1
r1_star_result1_10 <- eigenvalue1_10[1]
sqrt(r1_star_result1_10)

[1] 0.3140642

In [10]:
# canonical correlation 2
r2_star_result1_10 <- eigenvalue1_10[2]
sqrt(r2_star_result1_10)

[1] 0.1779097

### Canonical Correlation for Result 2

In [11]:
result2_10 <- sqrtm(solve(R22_10))%*%R21_10%*%solve(R11_10)%*%R12_10%*%sqrtm(solve(R22_10))
result2_10

[,1]       [,2]      
[1,] 0.08342666 0.02806202
[2,] 0.02806202 0.04686152

In [12]:
eigenvalue2_10 <- eigen(result2_10)$value
eigenvalue2_10

[1] 0.09863632 0.03165187

In [13]:
eigenvector2_10 <- eigen(result2_10)$vectors
eigenvector2_10

[,1]       [,2]      
[1,] -0.8791686  0.4765107
[2,] -0.4765107 -0.8791686

In [14]:
a1_result2_10 <- sqrtm(solve(R22_10))%*%eigenvector2_10[,1]
a1_result2_10

[,1]      
[1,] -0.9715295
[2,] -0.6140876

In [15]:
b1_result2_10 <- solve(R11_10)%*%R12_10%*%a1_result2_10
b1_result2_10

[,1]      
[1,] 0.05878802
[2,] 0.27446965

In [16]:
scale_result2_10 <- 1/(sqrtm(t(b1_result2_10)%*%R22_10%*%b1_result2_10))
newb1_result2_10 <- (scale_result2_10[1,1])*b1_result2_10
newb1_result2_10

[,1]     
[1,] 0.2220255
[2,] 1.0365932

In [17]:
# canonical correlation 1
r1_star_result2_10 <- eigenvalue2_10[1]
sqrt(r1_star_result2_10)

[1] 0.3140642

In [18]:
# canonical correlation 2
r2_star_result2_10 <- eigenvalue2_10[2]
sqrt(r2_star_result2_10)

[1] 0.1779097

## (b) Determine the first canonical pair U1, V1 and interpret these quantities. 

In [19]:
t(eigenvector1_10[, 1]) %*% sqrtm(solve(R11_10))

[,1]      [,2]     
[1,] 0.1871847 0.8739285

# 10.11

Example 8.5 presents the correlation matrix obtained from n = 100 successive weekly rates of return for five stocks. Perform a canonical correlation analysis with $X^{(1)}$ = [$X_{1}^{(1)}$, $X_{2}^{(1)}$, $X_{3}^{(1)}$]', the rates of return for the chemical companies, and $X^{(2)}$ = [$X_{1}^{(2)}$, $X_{2}^{(2)}$]'
, the rates of return for the oil companies.

In [20]:
xbar_11 <- matrix(c( .0054, .0048, .0057, .0063, .0037))
t(xbar_11)

[,1]   [,2]   [,3]   [,4]   [,5]  
[1,] 0.0054 0.0048 0.0057 0.0063 0.0037

In [21]:
R11_11 <- matrix(c(1, .577, .509,
                .577, 1, .599,
                .509, .599, 1),3,3)
R12_11 <- matrix(c(.387, .389,
                .436, .462,
                .322, .426),3,2)
R21_11 <- matrix(c(.387, .462, .389,
                .322, .436, .426),2,3)
R22_11 <- matrix(c(1, .523,
                .523, 1),2,2)

## Canonical Correlation

### Canonical Correlation for Result 1

In [22]:
result1_11 <- sqrtm(solve(R11_11))%*%R12_11%*%solve(R22_11)%*%R21_11%*%sqrtm(solve(R11_11))
result1_11

[,1]       [,2]       [,3]      
[1,] 0.14666732 0.06653671 0.13570327
[2,] 0.06653671 0.05842272 0.08148331
[3,] 0.13570327 0.08148331 0.13961186

In [23]:
eigenvalue1_11 <- eigen(result1_11)$value
eigenvalue1_11

[1] 3.206250e-01 2.407693e-02 3.873474e-17

In [24]:
eigenvector1_11 <- eigen(result1_11)$vectors
eigenvector1_11

[,1]       [,2]       [,3]      
[1,] -0.6552449  0.6116750 -0.4432920
[2,] -0.3708048 -0.7716914 -0.5167166
[3,] -0.6581473 -0.1742011  0.7324590

In [25]:
a1_result1_11 <- sqrtm(solve(R11_11))%*%eigenvector1_11[,1]
a1_result1_11

[,1]       
[1,] -0.54645947
[2,] -0.06514049
[3,] -0.55269225

In [26]:
b1_result1_11 <- sqrtm(solve(R22_11))%*%R21_11%*%a1_result1_11
b1_result1_11

[,1]      
[1,] -0.3772472
[2,] -0.4222671

In [27]:
scale_result1_11 <- 1/(sqrtm(t(b1_result1_11)%*%R22_11%*%b1_result1_11))
newb1_result1_11 <- (scale_result1_11[1,1])*b1_result1_11
newb1_result1_11

[,1]      
[1,] -0.5404422
[2,] -0.6049376

In [28]:
# canonical correlation 1
r1_star_result1_11 <- eigenvalue1_11[1]
sqrt(r1_star_result1_11)

[1] 0.5662376

In [29]:
# canonical correlation 2
r2_star_result1_11 <- eigenvalue1_11[2]
sqrt(r2_star_result1_11)

[1] 0.1551674

In [30]:
# canonical correlation 3
r3_star_result1_11 <- eigenvalue1_11[3]
sqrt(r3_star_result1_11)

[1] 6.223724e-09

### Canonical Correlation for Result 2

In [31]:
result2_11 <- sqrtm(solve(R22_11))%*%R21_11%*%solve(R11_11)%*%R12_11%*%sqrtm(solve(R22_11))
result2_11

[,1]      [,2]     
[1,] 0.1557054 0.1473367
[2,] 0.1473367 0.1889965

In [32]:
eigenvalue2_11 <- eigen(result2_11)$value
eigenvalue2_11

[1] 0.32062497 0.02407693

In [33]:
eigenvector2_11 <- eigen(result2_11)$vectors
eigenvector2_11

[,1]      [,2]      
[1,] 0.6662348 -0.7457420
[2,] 0.7457420  0.6662348

In [34]:
a1_result2_11 <- sqrtm(solve(R22_11))%*%eigenvector2_11[,1]
a1_result2_11

[,1]     
[1,] 0.5145084
[2,] 0.6296275

In [35]:
b1_result2_11 <- sqrtm(solve(R11_11))%*%R12_11%*%a1_result2_11
b1_result2_11

[,1]     
[1,] 0.3710243
[2,] 0.2099636
[3,] 0.3726677

In [36]:
scale_result2_11 <- 1/(sqrtm(t(b1_result2_11)%*%R11_11%*%b1_result2_11))
newb1_result2_11 <- (scale_result2_11[1,1])*b1_result2_11
newb1_result2_11

[,1]     
[1,] 0.4619719
[2,] 0.2614311
[3,] 0.4640182

In [37]:
# canonical correlation 1
r1_star_result2_11 <- eigenvalue2_11[1]
sqrt(r1_star_result2_11)

[1] 0.5662376

In [38]:
# canonical correlation 2
r2_star_result2_11 <- eigenvalue2_11[2]
sqrt(r2_star_result2_11)

[1] 0.1551674

## Canonical Correlations Sample

In [39]:
# result 1
canon.corr_11 <- sqrt(eigenvalue1_11)
canon.corr_11

[1] 5.662376e-01 1.551674e-01 6.223724e-09

In [40]:
# result 2
canon.corr_11 <- sqrt(eigenvalue2_11)
canon.corr_11

[1] 0.5662376 0.1551674

## Canonical Variables 

In [41]:
coeff.1 <- matrix(rep(0, 9), ncol = 3)
for(i in 1:nrow(eigenvector1_11)){
  coeff.1[i, ] <- t(eigenvector1_11[, i]) %*% sqrtm(solve(R11_11))
}
coeff.1

[,1]       [,2]        [,3]      
[1,] -0.5464595 -0.06514049 -0.5526922
[2,]  1.0075458 -1.11742730 -0.0883301
[3,] -0.5339486 -0.77112789  1.1619423

In [42]:
coeff.2 <- matrix(rep(0, 4), ncol = 2)
for(i in 1:nrow(eigenvector2_11)){
  coeff.2[i, ] <- t(eigenvector2_11[, i]) %*% sqrtm(solve(R22_11))
}
coeff.2

[,1]       [,2]     
[1,]  0.5145084 0.6296275
[2,] -1.0544186 0.9899933

## Canonical Loadings dan Canonical Cross Loadings for $U_1$ dan $V_1$

In [43]:
var.x1 <- diag(R11_11)
var.x2 <- diag(R22_11)

In [44]:
R_U1_X1 <- coeff.1[1, ] %*% R11_11 %*% solve(sqrt(diag(var.x1)))
R_U1_X1

R_U1_X2 <- coeff.1[1, ] %*% R12_11 %*% solve(sqrt(diag(var.x2)))
R_U1_X2

R_V1_X1 <- coeff.2[1, ] %*% R21_11 %*% solve(sqrt(diag(var.x1)))
R_V1_X1

R_V1_X2 <- coeff.2[1, ] %*% R22_11 %*% solve(sqrt(diag(var.x2)))
R_V1_X2

[,1]       [,2]       [,3]      
[1,] -0.8653659 -0.7115103 -0.8698593

[,1]       [,2]      
[1,] -0.4777933 -0.5088864

[,1]      [,2]      [,3]    
[1,] 0.4900027 0.4028838 0.492547

[,1]      [,2]     
[1,] 0.8438036 0.8987154

## Uji Signifikansi Korelasi Kanonik

$$
H_0 : \sigma_{12} = 0 \\
H_1 : \sigma_{12} \neq 0
$$

In [45]:
n = 100
p = 3
q = 2

stat.hit <- -(n-1-0.5*(p+q+1))*log((1-canon.corr_11[1]^2) * (1-canon.corr_11[2]^2))

stat.uji <- qchisq(0.95, p*q)

if(stat.hit > stat.uji){
  cat(stat.hit, ">", stat.uji, ", maka: ")
  cat("Tolak Ho")
}else{
  cat(stat.hit, "<", stat.uji, ", maka: ")
  cat("Gagal Tolak Ho")
}

39.45154 > 12.59159 , maka: Tolak Ho

# 11.8

Use the diabetes data of Table 3.5. 

In [46]:
diabetes <- read.xlsx("tabel_3.5.xlsx")
diabetes <- diabetes[,-1]
head(diabetes)

y1   y2  x1  x2  x3 
1 0.81  80 356 124  55
2 0.95  97 289 117  76
3 0.94 105 319 143 105
4 1.04  90 356 199 108
5 1.00  90 323 240 143
6 0.76  86 381 157 165

In [47]:
cor_diabetes <- cor(diabetes)
cor_diabetes

y1         y2          x1          x2         x3          
y1  1.0000000  0.16047812 0.175680799 -0.1438253  0.332284598
y2  0.1604781  1.00000000 0.072133311 -0.1132752 -0.170017219
x1  0.1756808  0.07213331 1.000000000  0.1638133  0.008216539
x2 -0.1438253 -0.11327520 0.163813321  1.0000000  0.368282904
x3  0.3322846 -0.17001722 0.008216539  0.3682829  1.000000000

In [48]:
R11_8 <- cor_diabetes[c(1,2),c(1,2)]
R11_8

y1        y2       
y1 1.0000000 0.1604781
y2 0.1604781 1.0000000

In [49]:
R12_8 <- cor_diabetes[c(1,2),c(3,4,5)]
R12_8

x1         x2         x3        
y1 0.17568080 -0.1438253  0.3322846
y2 0.07213331 -0.1132752 -0.1700172

In [50]:
R21_8 <- cor_diabetes[c(3,4,5),c(1,2)]
R21_8

y1         y2         
x1  0.1756808  0.07213331
x2 -0.1438253 -0.11327520
x3  0.3322846 -0.17001722

In [51]:
R22_8 <- cor_diabetes[c(3,4,5),c(3,4,5)]
R22_8

x1          x2        x3         
x1 1.000000000 0.1638133 0.008216539
x2 0.163813321 1.0000000 0.368282904
x3 0.008216539 0.3682829 1.000000000

## (a) Find the canonical correlations between $(y_{1}, y_{2})$ and $(x_{1}, x_{2}, x_{3})$. 

### Result 1

In [52]:
result1 <- sqrtm(solve(R11_8))%*%R12_8%*%solve(R22_8)%*%R21_8%*%sqrtm(solve(R11_8))
result1

[,1]        [,2]       
[1,]  0.25209303 -0.04570245
[2,] -0.04570245  0.04496109

In [53]:
eigenvalue1_8 <- eigen(result1)$value
eigenvalue1_8

[1] 0.26172876 0.03532536

In [54]:
eigenvector1_8 <- eigen(result1)$vectors
eigenvector1_8

[,1]       [,2]      
[1,] -0.9784886 -0.2063007
[2,]  0.2063007 -0.9784886

In [55]:
a1_result1_8 <- sqrtm(solve(R11_8))%*%eigenvector1_8[,1]
a1_result1_8

[,1]      
[1,] -1.0049450
[2,]  0.2881343

In [56]:
b1_result1_8 <- solve(R22_8)%*%R21_8%*%a1_result1_8
b1_result1_8

[,1]      
x1 -0.2058369
x2  0.3308953
x3 -0.5030873

In [57]:
scale_result1_8 <- 1/(sqrtm(t(b1_result1_8)%*%R22_8%*%b1_result1_8))
newb1_result1_8 <- (scale_result1_8[1,1])*b1_result1_8
newb1_result1_8

[,1]      
x1 -0.4023439
x2  0.6467924
x3 -0.9833716

In [58]:
# canonical correlation 1
r1_star_result1_8 <- eigenvalue1_8[1]
sqrt(r1_star_result1_8)

[1] 0.5115943

In [59]:
# canonical correlation 2
r2_star_result1_8 <- eigenvalue1_8[2]
sqrt(r2_star_result1_8)

[1] 0.1879504

### Result 2

In [60]:
result2 <- sqrtm(solve(R22_8))%*%R21_8%*%solve(R11_8)%*%R12_8%*%sqrtm(solve(R22_8))
result2

[,1]        [,2]        [,3]       
[1,]  0.04139904 -0.04964386  0.06534933
[2,] -0.04964386  0.05953903 -0.07924470
[3,]  0.06534933 -0.07924470  0.19611605

In [61]:
eigenvalue2_8 <- eigen(result2)$value
eigenvalue2_8

[1] 2.617288e-01 3.532536e-02 1.437032e-17

In [62]:
eigenvector2_8 <- eigen(result2)$vectors
eigenvector2_8

[,1]       [,2]       [,3]       
[1,]  0.3433701  0.5462432 0.764012699
[2,] -0.4146030 -0.6417610 0.645172251
[3,]  0.8427345 -0.5382948 0.006112527

In [63]:
a1_result2_8 <- sqrtm(solve(R22_8))%*%eigenvector2_8[,1]
a1_result2_8

[,1]      
[1,]  0.4023439
[2,] -0.6467924
[3,]  0.9833716

In [64]:
b1_result2_8 <- solve(R11_8)%*%R12_8%*%a1_result2_8
b1_result2_8

[,1]      
y1  0.5141242
y2 -0.1474079

In [65]:
scale_result2_8 <- 1/(sqrtm(t(b1_result2_8)%*%R11_8%*%b1_result2_8))
newb1_result2_8 <- (scale_result2_8[1,1])*b1_result2_8
newb1_result2_8

[,1]      
y1  1.0049450
y2 -0.2881343

In [66]:
# canonical correlation 1
r1_star_result2_8 <- eigenvalue2_8[1]
sqrt(r1_star_result2_8)

[1] 0.5115943

In [67]:
# canonical correlation 2
r2_star_result2_8 <- eigenvalue2_8[2]
sqrt(r2_star_result2_8)

[1] 0.1879504

In [68]:
# canonical correlation 3
r2_star_result2_8 <- eigenvalue2_8[3]
sqrt(r2_star_result2_8)

[1] 3.790821e-09

## (b) Find the standardized coefficients for the canonical variates. 

Karena pada bagian (a) menggunakan matriks korelasi dengan asumsi masukan data merupakan data yang terstandardisasi, maka nilai koefisien yang terstandardisasinya tetap sama, yaitu

In [69]:
a1_result1_8
a1_result2_8

[,1]      
[1,] -1.0049450
[2,]  0.2881343

[,1]      
[1,]  0.4023439
[2,] -0.6467924
[3,]  0.9833716

In [70]:
newb1_result1_8
newb1_result2_8

[,1]      
x1 -0.4023439
x2  0.6467924
x3 -0.9833716

[,1]      
y1  1.0049450
y2 -0.2881343

## (c) Test the significance of each canonical correlation. 

### Result 1

In [71]:
canon.corr1_8 <- sqrt(eigenvalue1_8)
canon.corr1_8

[1] 0.5115943 0.1879504

In [72]:
n = 39
p = 2
q = 3

stat.hit <- -(n-1-0.5*(p+q+1))*log((1-canon.corr1_8[1]^2) * (1-canon.corr1_8[2]^2))

stat.uji <- qchisq(0.95, p*q)

if(stat.hit > stat.uji){
  cat(stat.hit, ">", stat.uji, ", maka: ")
  cat("Tolak Ho")
}else{
  cat(stat.hit, "<", stat.uji, ", maka: ")
  cat("Gagal Tolak Ho")
}

11.87929 < 12.59159 , maka: Gagal Tolak Ho

### Result 2

In [73]:
canon.corr2_8 <- sqrt(eigenvalue2_8)
canon.corr2_8

[1] 5.115943e-01 1.879504e-01 3.790821e-09

In [74]:
n = 39
p = 2
q = 3

stat.hit <- -(n-1-0.5*(p+q+1))*log((1-canon.corr2_8[1]^2) * (1-canon.corr2_8[2]^2))

stat.uji <- qchisq(0.95, p*q)

if(stat.hit > stat.uji){
  cat(stat.hit, ">", stat.uji, ", maka: ")
  cat("Tolak Ho")
}else{
  cat(stat.hit, "<", stat.uji, ", maka: ")
  cat("Gagal Tolak Ho")
}

11.87929 < 12.59159 , maka: Gagal Tolak Ho

# 11.9

In [75]:
son <- read.xlsx("Son.xlsx")
head(son)

y1  y2  x1  x2 
1 191 155 179 145
2 195 149 201 152
3 181 148 185 149
4 183 153 188 149
5 176 144 171 142
6 208 157 192 152

In [76]:
cor_son <- cor(son)
cor_son

y1        y2        x1        x2       
y1 1.0000000 0.7345555 0.7107518 0.7039807
y2 0.7345555 1.0000000 0.6931573 0.7085504
x1 0.7107518 0.6931573 1.0000000 0.8392519
x2 0.7039807 0.7085504 0.8392519 1.0000000

In [77]:
R11_9 <- cor_son[c(1,2),c(1,2)]
R11_9

y1        y2       
y1 1.0000000 0.7345555
y2 0.7345555 1.0000000

In [78]:
R12_9 <- cor_son[c(1,2),c(3,4)]
R12_9

x1        x2       
y1 0.7107518 0.7039807
y2 0.6931573 0.7085504

In [79]:
R21_9 <- cor_son[c(3,4),c(1,2)]
R21_9

y1        y2       
x1 0.7107518 0.6931573
x2 0.7039807 0.7085504

In [80]:
R22_9 <- cor_son[c(3,4),c(3,4)]
R22_9

x1        x2       
x1 1.0000000 0.8392519
x2 0.8392519 1.0000000

## (a) Find the canonical correlations between $(y_{1}, y_{2})$ and $(x_{1}, x_{2})$. 

### Result 1

In [81]:
result1_9 <- sqrtm(solve(R11_9))%*%R12_9%*%solve(R22_9)%*%R21_9%*%sqrtm(solve(R11_9))
result1_9

[,1]      [,2]     
[1,] 0.3192267 0.3093512
[2,] 0.3093512 0.3054060

In [82]:
eigenvalue1_9 <- eigen(result1_9)$value
eigenvalue1_9

[1] 0.621744734 0.002887956

In [83]:
eigenvector1_9 <- eigen(result1_9)$vectors
eigenvector1_9

[,1]       [,2]      
[1,] -0.7149589  0.6991664
[2,] -0.6991664 -0.7149589

In [84]:
a1_result1_9 <- sqrtm(solve(R11_9))%*%eigenvector1_9[,1]
a1_result1_9

[,1]      
[1,] -0.5521896
[2,] -0.5215372

In [85]:
b1_result1_9 <- solve(R22_9)%*%R21_9%*%a1_result1_9
b1_result1_9

[,1]      
x1 -0.3977615
x2 -0.4244441

In [86]:
scale_result1_9 <- 1/(sqrtm(t(b1_result1_9)%*%R22_9%*%b1_result1_9))
newb1_result1_9 <- (scale_result1_9[1,1])*b1_result1_9
newb1_result1_9

[,1]      
x1 -0.5044484
x2 -0.5382877

In [87]:
# canonical correlation 1
r1_star_result1_9 <- eigenvalue1_9[1]
sqrt(r1_star_result1_9)

[1] 0.7885079

In [88]:
# canonical correlation 2
r2_star_result1_9 <- eigenvalue1_9[2]
sqrt(r2_star_result1_9)

[1] 0.0537397

### Result 2

In [89]:
result2_9 <- sqrtm(solve(R22_9))%*%R21_9%*%solve(R11_9)%*%R12_9%*%sqrtm(solve(R22_9))
result2_9

[,1]      [,2]     
[1,] 0.3063796 0.3093714
[2,] 0.3093714 0.3182531

In [90]:
eigenvalue2_9 <- eigen(result2_9)$value
eigenvalue2_9

[1] 0.621744734 0.002887956

In [91]:
eigenvector2_9 <- eigen(result2_9)$vectors
eigenvector2_9

[,1]      [,2]      
[1,] 0.7002906 -0.7138579
[2,] 0.7138579  0.7002906

In [92]:
a1_result2_9 <- sqrtm(solve(R22_9))%*%eigenvector2_9[,1]
a1_result2_9

[,1]     
[1,] 0.5044484
[2,] 0.5382877

In [93]:
b1_result2_9 <- solve(R11_9)%*%R12_9%*%a1_result2_9
b1_result2_9

[,1]     
y1 0.4354059
y2 0.4112362

In [94]:
scale_result2_9 <- 1/(sqrtm(t(b1_result2_9)%*%R11_9%*%b1_result2_9))
newb1_result2_9 <- (scale_result2_9[1,1])*b1_result2_9
newb1_result2_9

[,1]     
y1 0.5521896
y2 0.5215372

In [95]:
# canonical correlation 1
r1_star_result2_9 <- eigenvalue2_9[1]
sqrt(r1_star_result2_9)

[1] 0.7885079

In [96]:
# canonical correlation 2
r2_star_result2_9 <- eigenvalue2_9[2]
sqrt(r2_star_result2_9)

[1] 0.0537397

## (b) Find the standardized coefficients for the canonical variates. 
 

Karena pada bagian (a) menggunakan matriks korelasi dengan asumsi masukan data merupakan data yang terstandardisasi, maka nilai koefisien yang terstandardisasinya tetap sama, yaitu

In [97]:
a1_result1_9
a1_result2_9

[,1]      
[1,] -0.5521896
[2,] -0.5215372

[,1]     
[1,] 0.5044484
[2,] 0.5382877

In [98]:
newb1_result1_9
newb1_result2_9

[,1]      
x1 -0.5044484
x2 -0.5382877

[,1]     
y1 0.5521896
y2 0.5215372

## (c) Test the significance of each canonical correlation.

### Result 1

In [99]:
canon.corr1_9 <- sqrt(eigenvalue1_9)
canon.corr1_9

[1] 0.7885079 0.0537397

In [100]:
n = 25
p = 2
q = 2

stat.hit <- -(n-1-0.5*(p+q+1))*log((1-canon.corr1_9[1]^2) * (1-canon.corr1_9[2]^2))

stat.uji <- qchisq(0.95, p*q)

if(stat.hit > stat.uji){
  cat(stat.hit, ">", stat.uji, ", maka: ")
  cat("Tolak Ho")
}else{
  cat(stat.hit, "<", stat.uji, ", maka: ")
  cat("Gagal Tolak Ho")
}

20.96418 > 9.487729 , maka: Tolak Ho

### Result 2

In [101]:
canon.corr2_9 <- sqrt(eigenvalue2_9)
canon.corr2_9

[1] 0.7885079 0.0537397

In [102]:
n = 25
p = 2
q = 2

stat.hit <- -(n-1-0.5*(p+q+1))*log((1-canon.corr2_9[1]^2) * (1-canon.corr2_9[2]^2))

stat.uji <- qchisq(0.95, p*q)

if(stat.hit > stat.uji){
  cat(stat.hit, ">", stat.uji, ", maka: ")
  cat("Tolak Ho")
}else{
  cat(stat.hit, "<", stat.uji, ", maka: ")
  cat("Gagal Tolak Ho")
}

20.96418 > 9.487729 , maka: Tolak Ho