# Dataset

In [1]:
library(readxl)

Warning message:
"package 'readxl' was built under R version 3.6.3"

In [2]:
data <- read_excel("Tugas2_APG.xlsx")
data

x1 x2 x3
1 9  12 3 
2 2   8 4 
3 6   6 0 
4 5   4 2 
5 8  10 1

# Matriks S

## Menggunakan Function

### Matriks covariants

In [3]:
sn = cov(data)
sn

x1    x2   x3   
x1  7.50  5.0 -1.75
x2  5.00 10.0  1.50
x3 -1.75  1.5  2.50

### Eigen value and eigen vector

In [4]:
eigen(sn)

eigen() decomposition
$values
[1] 13.9049009  5.4143634  0.6807358

$vectors
             [,1]       [,2]       [,3]
[1,] -0.613679310  0.6232975  0.4846627
[2,] -0.789496144 -0.4769002 -0.3863444
[3,] -0.009671757 -0.6197309  0.7847548


## Syntax Manual

### Covarians Matrix

In [5]:
xbar1 = mean(data$x1)
xbar2 = mean(data$x2)
xbar3 = mean(data$x3)

In [6]:
x = 0
y = 0
z = 0
for (i in 1:5) {
    x = (data[i,1]-xbar1)^2 + x
    y = (data[i,1]-xbar1)*(data[i,2]-xbar2) + y
    z = (data[i,1]-xbar1)*(data[i,3]-xbar3) + z
}
s11 = x/4
s12 = y/4
s13 = z/4
s1 <- matrix(c(s11, s12, s13))
s1

[,1] 
[1,] 7.5  
[2,] 5    
[3,] -1.75

In [7]:
x = 0
y = 0
z = 0
for (i in 1:5) {
    x = (data[i,2]-xbar2)*(data[i,1]-xbar1) + x
    y = (data[i,2]-xbar2)^2 + y
    z = (data[i,2]-xbar2)*(data[i,3]-xbar3) + z
}
s21 = x/4
s22 = y/4
s23 = z/4
s2 <- matrix(c(s21, s22, s23))
s2

[,1]
[1,] 5   
[2,] 10  
[3,] 1.5

In [8]:
x = 0
y = 0
z = 0
for (i in 1:5) {
    x = (data[i,3]-xbar3)*(data[i,1]-xbar1) + x
    y = (data[i,3]-xbar3)*(data[i,2]-xbar2) + y
    z = (data[i,3]-xbar3)^2 + z
}
s31 = x/4
s32 = y/4
s33 = z/4
s3 <- matrix(c(s31, s32, s33))
s3

[,1] 
[1,] -1.75
[2,] 1.5  
[3,] 2.5

In [9]:
sn <- matrix(c(s1, s2, s3), 3, 3)
data.matrix(sn)

[,1]  [,2] [,3] 
[1,] 7.5   5    -1.75
[2,] 5     10   1.5  
[3,] -1.75 1.5  2.5

Berdasarkan syntax tersebut, dapat diketahui bahwa matriks yang dibuat menggunakan syntax manual sama dengan matriks yang menggunakan fungsi cov().

### Correlation Matrix

In [10]:
#mencari D^(-0.5)
matrixDiagonal<-matrix(c(s11^(-0.5),0,0,0,s22^(-0.5),0,0,0,s33^(-0.5)),3,3)
matrixDiagonal

[,1]      [,2]      [,3]     
[1,] 0.3651484 0         0        
[2,] 0         0.3162278 0        
[3,] 0         0         0.6324555

In [11]:
#matrix Correlation
mc <- matrixDiagonal%*%sn%*%matrixDiagonal
mc

ERROR: Error in matrixDiagonal %*% as.matrix(sn): requires numeric/complex matrix/vector arguments


Berdasarkan syntax tersebut, dapat diketahui bahwa matriks yang dibuat menggunakan syntax manual sama dengan matriks yang menggunakan fungsi cor().

# Matriks R

## Matriks covariants

In [12]:
r = cor(data)
r

x1         x2        x3        
x1  1.0000000 0.5773503 -0.4041452
x2  0.5773503 1.0000000  0.3000000
x3 -0.4041452 0.3000000  1.0000000

## Eigen value and eigen vector

In [13]:
eigen(r)

eigen() decomposition
$values
[1] 1.591638 1.273514 0.134848

$vectors
           [,1]       [,2]       [,3]
[1,]  0.7490653 -0.2047782  0.6300533
[2,]  0.6347139  0.4943479 -0.5939347
[3,] -0.1898407  0.8447994  0.5002744
