In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import sklearn.preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
from matplotlib.colors import ListedColormap

In [2]:
data = pd.read_excel('3SI1_Dataset 03_Gejala Ikutan Vaksin.xlsx')
data.head()

Sex          Age         Professions        Education Living Area  \
0    Male  51-55 years  Medical specialist    Master degree    Downtown   
1  Female  41-45 years   Non medical staff    Master degree    Downtown   
2    Male  56-60 years      Medical doctor              NaN    Downtown   
3    Male  26-30 years   Non medical staff              NaN    Downtown   
4  Female  31-35 years      Medical doctor  Bachelor degree    Downtown   

  1. Swelling 2. Redness 3. Itching 4. Fever 5. Headache  ... 8. Coughing  \
0          No         No         No       No          No  ...          No   
1          No         No         No       No          No  ...          No   
2          No         No         No       No          No  ...          No   
3          No         No         No       No          No  ...          No   
4          No         No         No       No          No  ...         Yes   

  9. Diarrhea 10. Nausea and vomiting 11. Breathlessness 12. Joint Pain  \
0          No                      No                 No             No   
1          No                      No                 No             No   
2          No                      No                 No             No   
3          No                      No                 No             No   
4          No                      No                 No             No   

  13. Fainted 14. Anaphylactic Reaction 15. Tingling 16. Swollen Lymph Nodes  \
0          No                        No           No                      No   
1          No                        No           No                      No   
2          No                        No           No                      No   
3          No                        No           No                      No   
4          No                        No           No                      No   

  TARGET LABEL (SYMPTOM TIME)  
0                        None  
1                        None  
2                  < 24 hours  
3                        None  
4                  < 24 hours  

[5 rows x 22 columns]

In [3]:
#Info mengenai dataset 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 449 entries, 0 to 448
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Sex                          449 non-null    object
 1   Age                          449 non-null    object
 2   Professions                  449 non-null    object
 3   Education                    447 non-null    object
 4   Living Area                  449 non-null    object
 5   1. Swelling                  448 non-null    object
 6   2. Redness                   448 non-null    object
 7   3. Itching                   449 non-null    object
 8   4. Fever                     449 non-null    object
 9   5. Headache                  449 non-null    object
 10  6. Muscle Pain               448 non-null    object
 11  7. Tiredness                 448 non-null    object
 12  8. Coughing                  449 non-null    object
 13  9. Diarrhea                  449 no

In [4]:
data.keys()

Index(['Sex', 'Age', 'Professions', 'Education', 'Living Area', '1. Swelling',
       '2. Redness', '3. Itching', '4. Fever', '5. Headache', '6. Muscle Pain',
       '7. Tiredness', '8. Coughing', '9. Diarrhea', '10. Nausea and vomiting',
       '11. Breathlessness', '12. Joint Pain', '13. Fainted',
       '14. Anaphylactic Reaction', '15. Tingling', '16. Swollen Lymph Nodes',
       'TARGET LABEL (SYMPTOM TIME)'],
      dtype='object')

Jika kita lihat, terdapat 4 variabel independen, yaitu User ID, Gender, Age, dan Estimated Salary, serta 1 variabel dependen, yaitu Purchased.

Tetapi, saat split data nanti variabel User ID dan Gender akan dihapus karena tidak diperlukan.

In [5]:
#Statistik deskriptif
data.describe()

Sex          Age Professions        Education Living Area  \
count      449          449         449              447         449   
unique       2           10           5                4           2   
top     Female  26-30 years       Nurse  Bachelor degree    Downtown   
freq       326          105         227              345         305   

       1. Swelling 2. Redness 3. Itching 4. Fever 5. Headache  ...  \
count          448        448        449      449         449  ...   
unique           2          2          1        2           2  ...   
top             No         No         No       No          No  ...   
freq           400        438        449      439         329  ...   

       8. Coughing 9. Diarrhea 10. Nausea and vomiting 11. Breathlessness  \
count          449         449                     449                449   
unique           2           2                       2                  2   
top             No          No                      No                 No   
freq           405         433                     437                441   

       12. Joint Pain 13. Fainted 14. Anaphylactic Reaction 15. Tingling  \
count             449         449                       449          447   
unique              2           1                         2            2   
top                No          No                        No           No   
freq              442         449                       447          408   

       16. Swollen Lymph Nodes TARGET LABEL (SYMPTOM TIME)  
count                      449                         449  
unique                       2                           4  
top                         No                        None  
freq                       446                         184  

[4 rows x 22 columns]

In [6]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

for x in data.columns:
  data[x] = le.fit_transform(data[x])

data.head(10)

Sex  Age  Professions  Education  Living Area  1. Swelling  2. Redness  \
0    1    6            1          2            0            0           0   
1    0    4            3          2            0            0           0   
2    1    7            0          4            0            0           0   
3    1    1            3          4            0            0           0   
4    0    2            0          0            0            0           0   
5    1    5            3          0            0            2           2   
6    0    5            0          0            0            0           0   
7    0    7            0          2            0            0           0   
8    0    3            3          2            0            0           0   
9    1    6            4          2            0            0           0   

   3. Itching  4. Fever  5. Headache  ...  8. Coughing  9. Diarrhea  \
0           0         0            0  ...            0            0   
1           0         0            0  ...            0            0   
2           0         0            0  ...            0            0   
3           0         0            0  ...            0            0   
4           0         0            0  ...            1            0   
5           0         0            0  ...            0            0   
6           0         0            0  ...            0            0   
7           0         0            0  ...            0            0   
8           0         0            0  ...            0            0   
9           0         0            0  ...            0            0   

   10. Nausea and vomiting  11. Breathlessness  12. Joint Pain  13. Fainted  \
0                        0                   0               0            0   
1                        0                   0               0            0   
2                        0                   0               0            0   
3                        0                   0               0            0   
4                        0                   0               0            0   
5                        0                   0               0            0   
6                        0                   0               0            0   
7                        0                   0               0            0   
8                        0                   0               0            0   
9                        0                   0               0            0   

   14. Anaphylactic Reaction  15. Tingling  16. Swollen Lymph Nodes  \
0                          0             0                        0   
1                          0             0                        0   
2                          0             0                        0   
3                          0             0                        0   
4                          0             0                        0   
5                          0             0                        0   
6                          0             0                        0   
7                          0             0                        0   
8                          0             0                        0   
9                          0             0                        0   

   TARGET LABEL (SYMPTOM TIME)  
0                            3  
1                            3  
2                            1  
3                            3  
4                            1  
5                            1  
6                            3  
7                            3  
8                            0  
9                            1  

[10 rows x 22 columns]

In [7]:
#Mengecek missing values
data.isnull().values.any()

False

Karena missing value FALSE, artinya tidak ada missing value yang ditemukan pada dataset.

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
std_data = pd.DataFrame(scaler.fit_transform(data))

std_data.columns = data.columns
std_data

Sex       Age  Professions  Education  Living Area  1. Swelling  \
0    1.628007  1.716029    -2.201529   1.273103    -0.687118    -0.346288   
1   -0.614248  0.679718    -0.249927   1.273103    -0.687118    -0.346288   
2    1.628007  2.234184    -3.177330   3.079180    -0.687118    -0.346288   
3    1.628007 -0.874748    -0.249927   3.079180    -0.687118    -0.346288   
4   -0.614248 -0.356592    -3.177330  -0.532974    -0.687118    -0.346288   
..        ...       ...          ...        ...          ...          ...   
444 -0.614248  0.161563    -1.225728  -0.532974    -0.687118     2.763381   
445 -0.614248  1.197873    -0.249927  -0.532974     1.455354    -0.346288   
446 -0.614248  0.161563     0.725874  -0.532974    -0.687118    -0.346288   
447 -0.614248  0.679718    -0.249927  -0.532974    -0.687118    -0.346288   
448 -0.614248  0.161563    -0.249927   2.176142    -0.687118    -0.346288   

     2. Redness  3. Itching  4. Fever  5. Headache  ...  8. Coughing  \
0     -0.153118         0.0 -0.150927    -0.603938  ...    -0.329609   
1     -0.153118         0.0 -0.150927    -0.603938  ...    -0.329609   
2     -0.153118         0.0 -0.150927    -0.603938  ...    -0.329609   
3     -0.153118         0.0 -0.150927    -0.603938  ...    -0.329609   
4     -0.153118         0.0 -0.150927    -0.603938  ...     3.033899   
..          ...         ...       ...          ...  ...          ...   
444   -0.153118         0.0 -0.150927    -0.603938  ...    -0.329609   
445   -0.153118         0.0 -0.150927     1.655798  ...     3.033899   
446   -0.153118         0.0 -0.150927    -0.603938  ...    -0.329609   
447   -0.153118         0.0 -0.150927    -0.603938  ...    -0.329609   
448   -0.153118         0.0 -0.150927    -0.603938  ...    -0.329609   

     9. Diarrhea  10. Nausea and vomiting  11. Breathlessness  12. Joint Pain  \
0      -0.192228                 -0.16571           -0.134687       -0.125846   
1      -0.192228                 -0.16571           -0.134687       -0.125846   
2      -0.192228                 -0.16571           -0.134687       -0.125846   
3      -0.192228                 -0.16571           -0.134687       -0.125846   
4      -0.192228                 -0.16571           -0.134687       -0.125846   
..           ...                      ...                 ...             ...   
444    -0.192228                 -0.16571           -0.134687       -0.125846   
445    -0.192228                 -0.16571           -0.134687       -0.125846   
446    -0.192228                 -0.16571           -0.134687       -0.125846   
447    -0.192228                 -0.16571           -0.134687       -0.125846   
448    -0.192228                 -0.16571           -0.134687       -0.125846   

     13. Fainted  14. Anaphylactic Reaction  15. Tingling  \
0            0.0                   -0.06689      -0.30989   
1            0.0                   -0.06689      -0.30989   
2            0.0                   -0.06689      -0.30989   
3            0.0                   -0.06689      -0.30989   
4            0.0                   -0.06689      -0.30989   
..           ...                        ...           ...   
444          0.0                   -0.06689      -0.30989   
445          0.0                   -0.06689      -0.30989   
446          0.0                   -0.06689      -0.30989   
447          0.0                   -0.06689      -0.30989   
448          0.0                   -0.06689      -0.30989   

     16. Swollen Lymph Nodes  TARGET LABEL (SYMPTOM TIME)  
0                  -0.082015                     1.128763  
1                  -0.082015                     1.128763  
2                  -0.082015                    -0.503490  
3                  -0.082015                     1.128763  
4                  -0.082015                    -0.503490  
..                       ...                          ...  
444                -0.082015                    -1.319616  
445                -0.082015      

In [9]:
#Split data menjadi X dan y
X = data.drop(columns='TARGET LABEL (SYMPTOM TIME)')
y = data['TARGET LABEL (SYMPTOM TIME)']

In [10]:
#Split X dan y menjadi data training dan data testing
#25% untuk data testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [18]:
y_train

328    1
20     3
408    3
302    3
14     0
      ..
323    1
192    1
117    3
47     3
172    0
Name: TARGET LABEL (SYMPTOM TIME), Length: 336, dtype: int32

# Training model dengan kernel rbf

In [11]:
#Melakukan training model dengan SVC
model = SVC(kernel = 'rbf', random_state = 0)
model.fit(X_train, y_train)

SVC(random_state=0)

In [12]:
#Memprediksi hasil test data
y_pred =model.predict(X_test)

In [13]:
#Membuat confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 2 19  0  9]
 [ 0 21  0 15]
 [ 0  4  0  0]
 [ 0 11  0 32]]


0.48672566371681414

# Training model dengan kernel linear

In [14]:
model2 = SVC(kernel='linear',random_state=0)
model2.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [15]:
y_pred = model2.predict(X_test)

In [16]:
cm2 = confusion_matrix(y_test, y_pred)
print(cm2)
accuracy_score(y_test,y_pred)

[[12 18  0  0]
 [ 5 23  0  8]
 [ 2  2  0  0]
 [ 2 16  0 25]]


0.5309734513274337