In [26]:
n <- 20
p <- 3
d <- matrix(c(-44.05, 98.35, 41.65), ncol=3, byrow=T)
d

[,1]   [,2]  [,3] 
[1,] -44.05 98.35 41.65

In [27]:
xbar <- t(d)

In [28]:
S <- matrix(c(1748.89, 218.91, 718.67,
              218.91,  321.92, 345.23,
              718.67,  345.23, 1216.77), ncol=3, byrow=T)
S

[,1]    [,2]   [,3]   
[1,] 1748.89 218.91  718.67
[2,]  218.91 321.92  345.23
[3,]  718.67 345.23 1216.77

In [29]:
inv_S <- ((1/n)+(1/n))*solve(S)
inv_S

[,1]          [,2]          [,3]         
[1,]  7.556229e-05 -5.062095e-06 -4.319367e-05
[2,] -5.062095e-06  4.468293e-04 -1.237875e-04
[3,] -4.319367e-05 -1.237875e-04  1.428184e-04

In [30]:
d%*%inv_S%*%t(d)

[,1]    
[1,] 3.904646

In [31]:
df1 <- p
df2 <- n-p
critValue <- (n-1)*p/(n-p)*qf(0.05, df1, df2, lower.tail=F)
critValue

[1] 10.7186

In [32]:
  CI <- c()
  
  for(i in 1 : p){
    
    ## get standard error
    standardError <- sqrt(S[i, i] / n)
    
    Upper <- xbar[i] +  critValue*standardError
    Lower <- xbar[i] -  critValue*standardError
    
    CI <- rbind(CI, c(Lower, Upper))
  }
  
  CI <- as.data.frame(CI)
  colnames(CI) <- c("Lower_Bonferroni", "Upper_Bonferroni")
  
  return(CI)


Lower_Bonferroni Upper_Bonferroni
1 -144.28156        56.18156       
2   55.34715       141.35285       
3  -41.95409       125.25409

In [39]:
n1 <- 12
n2 <- 11
n3 <- 11
n <- 34
p <- 3
g <- 3

In [40]:
S1 <- matrix(c(44.13, 14.03, 23.68,
              14.03, 46.09, 24.26,
              23.68, 24.26, 31.89), ncol=3)
S2 <- matrix(c(58.44, 22.89, 39.17,
              22.89, 78.35, 54.81,
              39.17, 54.81, 66.44), ncol=3)
S3 <- matrix(c(82.55, 63.42, 41.18,
              63.42, 109.8, 081.91,
              41.18, 81.91, 85.53), ncol=3)

In [43]:
xbar1 <- matrix(c(76.04, 90.81, 85.91))
xbar2 <- matrix(c(71.64, 91.88, 89.72))
xbar3 <- matrix(c(73.91, 86.22, 85.28))
xbar <- matrix(c(73.93, 89.67, 86.94))

In [42]:
W <- (n1-1)*S1 + (n2-1)*S2 + (n3-1)*S3
W

[,1]    [,2]    [,3]   
[1,] 1895.33 1017.43 1063.98
[2,] 1017.43 2388.49 1634.06
[3,] 1063.98 1634.06 1870.49

In [45]:
B <- n1*(xbar1-xbar)%*%t(xbar1-xbar) + n2*(xbar2-xbar)%*%t(xbar2-xbar) + n3*(xbar3-xbar)%*%t(xbar3-xbar)
B

[,1]     [,2]     [,3]    
[1,] 111.1147 -26.0461 -95.7426
[2,] -26.0461 200.2478 116.4884
[3,] -95.7426 116.4884 128.0548

In [47]:
det(W)/det(B+W)

[1] 0.7197749

In [50]:
qt(0.05/(3*3*(3-1)), 34-3, lower.tail=F)

[1] 2.980556

In [52]:
n <- 12
p <- 3
df1 <- p
df2 <- n-p
critValue <- (n-1)*p/(n-p)*qf(0.05, df1, df2, lower.tail=F)
critValue

[1] 14.16268

In [ ]:
S1 <- matrix(c(44.13, 14.03, 23.68,
              14.03, 46.09, 24.26,
              23.68, 24.26, 31.89), ncol=3)